# Generated by Django 3.2.7 on 2021-10-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retromove', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='imagePath',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
