# Generated by Django 3.2.7 on 2021-11-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retromove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score_pacman',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score_snake',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
