# Generated by Django 3.2.7 on 2021-10-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retromove', '0002_auto_20211001_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imagePath',
            new_name='image',
        ),
    ]
